### ISSUE TITLE
Why was the minimum SDK changed to 24?

### ISSUE THREAD

**Issue by ZXHHYJ** [dshatz/compose-mpp-shared-element#1]
build log:
`Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [lib-android-1.0-beta01.aar] C:\Users\28343\.gradle\caches\transforms-3\9e1446e1c556a356fa0f43177d82e182\transformed\lib-android-1.0-beta01\AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.dshatz.sharedelements" to force usage (may lead to runtime failures)`
Why was the minimum SDK changed to 24?

**Comment by dshatz** [comment]
I believe it was a compose-multiplatform requirement for android. Can't find it now, will report next time I'm working on this.
